
# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/supply"
    username: postgres
    password: mkiniz@123
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  # jackson serialization
  jackson:
    default-property-inclusion: non-null
    deserialization:
      fail-on-ignored-properties: false
    mapper:
      accept-case-insensitive-properties: true
      accept-case-insensitive-values: true
      accept-case-insensitive-enums: true
      
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    #org.springframework: info
    org:
      hibernate: 
        orm:
          jdbc:
            bind: trace
        SQL: debug
            
        
# Server configuration
server:
  port: 8080 #set your port
  servlet:
    context-path: /supplychain

  

